from distutils.core import setup

setup(
      name             = 'sifes',
      version          = '2.0.0',
      description      = 'Pipeline for 16S microbial environmental sequencing',
      long_description = open('README.md').read(),
      license          = 'Proprietary software, all rights reserved.',
      url              = 'http://github.com/xapple/sifes/',
      author           = 'Lucas Sinclair',
      author_email     = 'lucas.sinclair@me.com',
      classifiers      = ['Topic :: Scientific/Engineering :: Bio-Informatics'],
      requires         = ['plumbing', 'fasta', 'pymarktex', 'sh', 'biopython', 'matplotlib',
                          'threadpool', 'patsy', 'pandas', 'statsmodels', 'rpy2',
                          'scikit-learn', 'rpy2', 'brewer2mpl', 'regex', 'ftputil',
                          'names', 'shell_command', 'pystache', 'tabulate', 'tqdm',
                          'scikit-bio'],
      packages         = ['sifes',
                          'sifes.clustering',
                          'sifes.clustering.composition',
                          'sifes.clustering.diversity',
                          'sifes.clustering.otu',
                          'sifes.clustering.reporting',
                          'sifes.clustering.source',
                          'sifes.clustering.statistics',
                          'sifes.clustering.taxonomy',
                          'sifes.graphs',
                          'sifes.groups',
                          'sifes.helper',
                          'sifes.reporting',
                          'sifes.running',
                          ],
)